repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        language: python
        pass_filenames: false
        entry: isort --settings-path=sdks/bk-storages/pyproject.toml sdks/bk-storages/
      - id: black
        name: black
        language: python
        pass_filenames: false
        entry: black --config=sdks/bk-storages/pyproject.toml sdks/bk-storages/
      - id: flake8
        name: flak8
        language: python
        pass_filenames: false
        entry: pflake8 --config=sdks/bk-storages/pyproject.toml sdks/bk-storages/
      - id: mypy
        name: mypy
        language: python
        pass_filenames: false
        entry: mypy sdks/bk-storages/bkstorages --config-file=sdks/bk-storages/pyproject.toml