repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        language: python
        pass_filenames: false
        entry: isort --settings-path=sdks/bkstorages/pyproject.toml .
      - id: black
        name: black
        language: python
        pass_filenames: false
        entry: black --config=sdks/bkstorages/pyproject.toml .
      - id: flake8
        name: flak8
        language: python
        pass_filenames: false
        entry: pflake8 --config=sdks/bkstorages/pyproject.toml
      - id: mypy
        name: mypy
        language: python
        pass_filenames: false
        entry: mypy bkstorages --config-file=sdks/bkstorages/pyproject.toml